### ISSUE TITLE
Where did you download APMDisable from?

### ISSUE THREAD

**Issue by levap5** [LordOfMice/Tools#3]
Where did you download APMDisable from?

**Comment by LordOfMice** [comment]
All files (except drivers in atsiv.zip and sbp2dos.zip; edid-decode is just build for Windows) are my own and sources available.

**Comment by levap5** [comment]
@LordOfMice Thank you for your reply. Where can I see APMDisable sources? The links in the readme of the repository don't work.

Edit: I can open http://sweetlow.orgfree.com/ but there are no sources

**Comment by LordOfMice** [comment]
>The links in the readme of the repository don't work.
> I can open http://sweetlow.orgfree.com/ but there are no sources

That is because I never publish any sources by default. But you can get them by direct request. And in case of APMDisable you can get similar code (and much more) from sources of CrystalDiskInfo.
